# For more information: https://laravel.com/docs/sail
version: '3'
services:
    db:
        image: 'postgres:latest'
        container_name: db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: nestjsapp
        networks:
            - nestjsapp
        healthcheck:
          retries: 3
          timeout: 5s
networks:
    nestjsapp:
        driver: bridge